#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.91.153:3500/eureka/
  instance:
    ip-address: 47.98.145.177
    #    ip-address: 127.0.0.1
    #    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #    lease-expiration-duration-in-seconds: 90
    #    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
#    lease-renewal-interval-in-seconds: 30
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    ip-address: ${spring.cloud.client.ip-address}
feign:
  hystrix:
    enabled: false
  client:
    config:
      share:
        connectTimeout: 120000
        readTimeout: 120000
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
    response:
      enabled: true